### ISSUE TITLE
Missing 'resources/resources.json'

### ISSUE THREAD

**Issue by giranntu** [carlomazzaferro/kryptoflow#2]
Thanks for building the interesting project!!

I knew it's WIP but I really want to try it.
I have tried the python3.6 kryptoflow/scrapers/reddit.py this one. 
But in the docker container there is no 'resources/resources.json' this file. (which defined in kryptoflow/kryptoflow/definitions.py)
Could you guide me how to generate resources.json this file? 
Seems like kafka cofig.

Thanks for the kindly support.

**Comment by carlomazzaferro** [comment]
No worries, I have lots of stuff still to be added to the README, this was one of them. If anythings thanks for the reminder. The `resources.json` file should look like this:

```
{
  "reddit": {
    "client_id": "XXXXXXXX",
    "client_secret": "XXXXXXXX",
    "username": "redditusername",
    "password": "redditpw",
    "user_agent": "testscript by /u/redditusername"   # optional
  },

  "twitter": {
    "consumer_key": "XXXXXXXXXXXX",
    "consumer_secret": "XXXXXXXXXXXX",
    "access_token": "XXXXXXXX",
    "access_secret": "XXXXXXXXX"
  }
}
```
These are the API keys for twitter and reddit. You will need to get them from your account settings on each of the platforms. Let me know if you run into any other problems.

**Comment by giranntu** [comment]
That's really helpful.

Also in just the start of docker container. 
when you just trying to run kryptoflow/scrapers/reddit.py

```
  File "/kryptoflow/kryptoflow/common/streamer_base.py", line 15, in __init__
    self.ip = os.environ['KAFKA_SERVER_IP']
```

The first thing should be define ['KAFKA_SERVER_IP'], since in container we didn't have this config.
How should I define the KAFKA SERVER IP?

**Comment by carlomazzaferro** [comment]
@giranntu 

Check out: https://github.com/carlomazzaferro/kryptoflow#dependencies

I was a bit off: you'll need to run `export KAFKA_SERVER_IP='kafka1'`, then, edit your `/etc/hosts` file and add: `127.0.0.1       localhost kafka1` as described in the README.
